spring:
  application:
    name: server

server:
  port: 8076

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     defaultZone: http://localhost:8076/eureka