spring:
  application:
    name: gateway

server:
  port: 8077
  servlet:
    context-path: /gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8076/eureka
  instance:
    prefer-ip-address: true

zuul:
  sensitive-headers: Cookie